// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFacturacion.DAL;

namespace SistemaFacturacion.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201113173031_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SistemaFacturacion.Entidades.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Cedula = "402-0000000-0",
                            NombreCompleto = "Jose Luis Burgos Hernandez",
                            Telefono = "809-000-0000"
                        },
                        new
                        {
                            ClienteId = 2,
                            Cedula = "402-0000000-0",
                            NombreCompleto = "asd asd asd asd",
                            Telefono = "809-000-0000"
                        });
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.Empleados", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Puesto")
                        .HasColumnType("TEXT");

                    b.Property<long>("Telefono")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmpleadoId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.EntradaProductos", b =>
                {
                    b.Property<int>("EntradaProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradaProductos");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.Facturacion", b =>
                {
                    b.Property<int>("FacturacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("FacturacionId");

                    b.ToTable("Facturacion");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.FacturacionDetalle", b =>
                {
                    b.Property<int>("FacturacionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<int>("FacturacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SubTotal")
                        .HasColumnType("REAL");

                    b.HasKey("FacturacionDetalleId");

                    b.HasIndex("FacturacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("FacturacionDetalle");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Existencia")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<string>("Suplidor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.HasIndex("SuplidorId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.SalidaProductos", b =>
                {
                    b.Property<int>("SalidaProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalidaProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("SalidaProductos");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            NombreComercial = "Supermercado Yoma"
                        },
                        new
                        {
                            SuplidorId = 2,
                            NombreComercial = "Grupo Rica"
                        },
                        new
                        {
                            SuplidorId = 3,
                            NombreComercial = "Surtidora Jose Luis"
                        },
                        new
                        {
                            SuplidorId = 4,
                            NombreComercial = "Omega Tech"
                        },
                        new
                        {
                            SuplidorId = 5,
                            NombreComercial = "NVIDIA"
                        });
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.EntradaProductos", b =>
                {
                    b.HasOne("SistemaFacturacion.Entidades.Productos", "productos")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productos");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.FacturacionDetalle", b =>
                {
                    b.HasOne("SistemaFacturacion.Entidades.Facturacion", null)
                        .WithMany("Detalle")
                        .HasForeignKey("FacturacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion.Entidades.Productos", "productos")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productos");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.Productos", b =>
                {
                    b.HasOne("SistemaFacturacion.Entidades.Suplidores", "suplidores")
                        .WithMany()
                        .HasForeignKey("SuplidorId");

                    b.Navigation("suplidores");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.SalidaProductos", b =>
                {
                    b.HasOne("SistemaFacturacion.Entidades.Productos", "productos")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productos");
                });

            modelBuilder.Entity("SistemaFacturacion.Entidades.Facturacion", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
